ARG IMAGE_BASE="centos"
ARG IMAGE_TAG="7"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG ETCD_VERSION="v3.4.14"
ARG APISIX_VERSION
ARG IMAGE_BASE
ARG IMAGE_TAG

ENV RUNNING_ETCD_VERSION=${ETCD_VERSION}



COPY ./output/apisix-local-master-0.el7.x86_64.rpm /output/apisix-local-master-0.el7.x86_64.rpm
COPY ./utils/install-common.sh /install-common.sh

RUN yum install -y wget
# install openresty
RUN /install-common.sh install_openresty_rpm

# install etcd
RUN /install-common.sh install_etcd

RUN rpm --import https://repos.apiseven.com/KEYS
RUN yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm


RUN yum -y localinstall /output/apisix-local-master-0.el7.x86_64.rpm

RUN which apisix
# start
CMD ["apisix","start"]
EXPOSE 9180 9080 9443
