ARG IMAGE_BASE="centos"
ARG IMAGE_TAG="7"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG ETCD_VERSION="v3.4.14"
ARG APISIX_VERSION
ARG IMAGE_BASE
ARG IMAGE_TAG

ENV RUNNING_ETCD_VERSION=${ETCD_VERSION}


COPY ./output/apisix-master-0.el7.x86_64.rpm /output/apisix-master-0.el7.x86_64.rpm
COPY ./output/apisix-base-latest-0.el7.x86_64.rpm  /output/apisix-base-latest-0.el7.x86_64.rpm
COPY ./utils/install-common.sh /install-common.sh
RUN yum update \
	yum install epel-release

RUN /install-common.sh install_apisix_dependencies_rpm
# install etcd
RUN /install-common.sh install_etcd

RUN rpm --import https://repos.apiseven.com/KEYS
RUN yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm

RUN yum -y localinstall /output/apisix-base-latest-0.el7.x86_64.rpm
RUN yum -y localinstall /output/apisix-master-0.el7.x86_64.rpm

# start etcd and test
CMD ["sh", "-c", "(nohup etcd-$RUNNING_ETCD_VERSION-linux-amd64/etcd >/tmp/etcd.log 2>&1 &) && sleep 10 && apisix start && sleep 3600"]
EXPOSE 9180 9080 9443
