ARG IMAGE_BASE="centos"
ARG IMAGE_TAG="7"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG ETCD_VERSION="v3.4.14"
ARG APISIX_VERSION
ARG IMAGE_BASE
ARG IMAGE_TAG

ENV RUNNING_ETCD_VERSION=${ETCD_VERSION}

COPY ./output/apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}.el7.x86_64.rpm /apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}.el7.x86_64.rpm
COPY ./utils/install-common.sh /install-common.sh

# install openresty
RUN /install-common.sh install_openresty_rpm

# install etcd
RUN /install-common.sh install_etcd

# install apisi
RUN set -x \
    && apt install -y libldap2-dev \
    && dpkg -i /apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}.el7.x86_64.rpm

RUN rpm --import https://repos.apiseven.com/KEYS
RUN yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm

RUN ls /output
RUN yum -y localinstall /output/apisix-local-master-0.el7.x86_64.rpm
# start etcd and test
CMD ["sh", "-c", "(nohup etcd-$RUNNING_ETCD_VERSION-linux-amd64/etcd >/tmp/etcd.log 2>&1 &) && sleep 10 && apisix start && sleep 3600"]
EXPOSE 9180 9080 9443
