ARG IMAGE_BASE="ubuntu"
ARG IMAGE_TAG="24.04"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG ETCD_VERSION="v3.4.14"
ARG APISIX_VERSION
ARG IMAGE_BASE
ARG IMAGE_TAG

ENV RUNNING_ETCD_VERSION=${ETCD_VERSION}

COPY ./output/apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}_amd64.deb /apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}_amd64.deb
COPY ./utils/install-common.sh /install-common.sh

# install
RUN set -x \
    && DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y libreadline-dev lsb-release libpcre3 libpcre3-dev libldap2-dev libssl-dev perl build-essential \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends wget gnupg ca-certificates \
    && wget -O - https://openresty.org/package/pubkey.gpg | apt-key add - \
    && wget -O - http://repos.apiseven.com/pubkey.gpg | apt-key add - \
    && echo "deb http://openresty.org/package/${arch_path}ubuntu $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/openresty.list \
    && echo "deb http://repos.apiseven.com/packages/debian bullseye main" | tee /etc/apt/sources.list.d/apisix.list \
    && DEBIAN_FRONTEND=noninteractive apt-get update

# install etcd
RUN /install-common.sh install_etcd

# install apisix
RUN set -x \
    && apt install -y libldap2-dev libyaml-dev \
    && dpkg -i /apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}_amd64.deb

# start etcd and test
CMD ["sh", "-c", "(nohup etcd-$RUNNING_ETCD_VERSION-linux-amd64/etcd >/tmp/etcd.log 2>&1 &) && sleep 10 && apisix start && sleep 3600"]

EXPOSE 9180 9080 9443
