# syntax=docker/dockerfile:1
ARG IMAGE_BASE="registry.access.redhat.com/ubi9/ubi"
ARG IMAGE_TAG="9.6"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

WORKDIR /tmp

ARG VERSION
ARG RUNTIME_VERSION
ARG IMAGE_BASE
ARG IMAGE_TAG
ARG CODE_PATH

ENV IMAGE_BASE=${IMAGE_BASE}
ENV IMAGE_TAG=${IMAGE_TAG}
ENV version=${VERSION}
ENV runtime_version=${RUNTIME_VERSION}

COPY ${CODE_PATH} ./

# the secret is optional: without it the runtime is built without
# ngx_http_ffi_client
RUN --mount=type=secret,id=ngx_http_ffi_client_token \
    export NGX_HTTP_FFI_CLIENT_TOKEN="$(cat /run/secrets/ngx_http_ffi_client_token 2>/dev/null || true)" \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && source "$HOME/.cargo/env" \
    && rustup install 1.69 \
    && rustup default 1.69 \
    # build apisix runtime
    && mv ./utils/build-common.sh ./utils/determine-dist.sh ./ \
    && ./build-common.sh build_apisix_runtime_rpm \
    # determine dist and write it into /tmp/dist file
    && ./determine-dist.sh
