ARG image_base="ubuntu"
ARG image_tag="20.04"
ARG iteration="0"
ARG apisix_repo="https://github.com/apache/apisix"
ARG checkout_v

FROM ${image_base}:${image_tag}

COPY ./utils/install-common.sh /install-common.sh

# install dependencies
RUN /install-common.sh install_apisix_dependencies_deb

ARG checkout_v
ARG iteration
ARG apisix_repo

ENV checkout_v=${checkout_v}
ENV iteration=${iteration}
ENV apisix_repo=${apisix_repo}

# install apisix
RUN /install-common.sh install_apisix
