ARG VERSION
ARG PACKAGE_TYPE

FROM apache/apisix-dashboard-${PACKAGE_TYPE}:${VERSION} AS APISIX
FROM api7/fpm

ARG ITERATION
ARG PACKAGE_VERSION
ARG PACKAGE_TYPE

ENV ITERATION=${ITERATION}
ENV PACKAGE_VERSION=${PACKAGE_VERSION}
ENV PACKAGE_TYPE=${PACKAGE_TYPE}

COPY --from=APISIX /tmp/build/output /tmp/build/output
COPY --from=APISIX /tmp/dist /tmp/dist
COPY package-apisix-dashboard.sh /package-apisix-dashboard.sh

RUN /package-apisix-dashboard.sh