ARG IMAGE_BASE="alpine"
ARG IMAGE_TAG="3.15"

FROM ${IMAGE_BASE}:${IMAGE_TAG} as build

COPY ./utils/build-common.sh \
     ./utils/install-common.sh \
     build-apisix-base.sh \
     ./utils/determine-dist.sh \
     /tmp/


ARG RESTY_OPENSSL_VERSION="3.0.8"
ARG RESTY_OPENSSL_PATCH_VERSION="3.0.8"
ARG RESTY_OPENSSL_URL_BASE="https://www.openssl.org/source"
ARG RESTY_PCRE_VERSION="8.44"
ARG RESTY_J="1"
ARG RESTY_EVAL_PRE_CONFIGURE=""
ARG VERSION

LABEL resty_image_base="${RESTY_IMAGE_BASE}"
LABEL resty_image_tag="${IMAGE_TAG}"
LABEL resty_openssl_version="${RESTY_OPENSSL_VERSION}"
LABEL resty_openssl_patch_version="${RESTY_OPENSSL_PATCH_VERSION}"
LABEL resty_openssl_url_base="${RESTY_OPENSSL_URL_BASE}"
LABEL resty_pcre_version="${RESTY_PCRE_VERSION}"
LABEL resty_eval_pre_configure="${RESTY_EVAL_PRE_CONFIGURE}"


ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

RUN apk add --no-cache \
        build-base \
        coreutils \
        curl \
        gd \
        gd-dev \
        geoip \
        geoip-dev \
        libxslt \
        libxslt-dev \
        linux-headers \
        make \
        perl-dev \
        readline-dev \
        zlib \
        zlib-dev \
        unzip \
        git \
        sudo \
        bash \
        libstdc++

# install latest Rust to build wasmtime
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN cd /tmp \
    && if [ -n "${RESTY_EVAL_PRE_CONFIGURE}" ]; then eval $(echo ${RESTY_EVAL_PRE_CONFIGURE}); fi \
    && cd /tmp \
    && curl -fSL "${RESTY_OPENSSL_URL_BASE}/openssl-${RESTY_OPENSSL_VERSION}.tar.gz" -o openssl-${RESTY_OPENSSL_VERSION}.tar.gz \
    && tar xzf openssl-${RESTY_OPENSSL_VERSION}.tar.gz \
    && cd openssl-${RESTY_OPENSSL_VERSION} \
    && ./config \
      no-threads shared zlib -g \
      enable-ssl3 enable-ssl3-method \
      --prefix=/usr/local/openssl \
      --openssldir=/usr/local/openssl \
      -Wl,-rpath,/usr/local/openssl/lib \
    && make -j${RESTY_J} \
    && make -j${RESTY_J} install_sw


RUN cd /tmp \
    && curl -fSL https://downloads.sourceforge.net/project/pcre/pcre/${RESTY_PCRE_VERSION}/pcre-${RESTY_PCRE_VERSION}.tar.gz -o pcre-${RESTY_PCRE_VERSION}.tar.gz \
    && tar xzf pcre-${RESTY_PCRE_VERSION}.tar.gz \
    && cd /tmp/pcre-${RESTY_PCRE_VERSION} \
    && ./configure \
        --prefix=/usr/local/openresty/pcre \
        --disable-cpp \
        --enable-jit \
        --enable-utf \
        --enable-unicode-properties \
    && make -j${RESTY_J} \
    && make -j${RESTY_J} install

ENV version=${VERSION}
RUN cd /tmp \
    && curl --version \
    && source /root/.cargo/env \
    && ./build-common.sh build_apisix_base_apk \
    && rm /usr/local/openresty/wasmtime-c-api/lib/libwasmtime.a \
    && rm /usr/local/openresty/wasmtime-c-api/lib/libwasmtime.d \
    && /usr/local/openresty/bin/openresty -V


FROM ${IMAGE_BASE}:${IMAGE_TAG} as prod

COPY --from=build /usr/local/openresty /usr/local/openresty

RUN apk add --no-cache \
        gd \
        geoip \
        libxslt \
        zlib \
        libstdc++ \
    && apk add --no-cache --virtual .build-deps \
        curl \
        make \
        sudo \
    && curl https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh -sL | sh - \
    && apk del .build-deps


ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

CMD /bin/sh
