name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  build_test:
    name: test package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: intall deps for fpm
      run: |
        sudo apt-get install ruby ruby-dev rubygems build-essential rpm
        sudo gem install --no-document fpm

    # should download the corresponding package from the specified address then test? how to know which package should download?
    - name: build apisix package
      run: |
        make package type=rpm app=apisix version=2.3 branch=2.3
        make package type=deb app=apisix version=2.3 branch=2.3

    - name: run centos docker containers for test
      run: |
        docker run -itd --rm \
            -v ${PWD}/output:/tmp/output \
            -v ${PWD}/test.sh:/tmp/test.sh \
            --name dockerInstance \
            --net="host" \
            docker.io/centos:7 /bin/bash

    - name: run rpm test
      run: |
        docker exec dockerInstance bash -c "/tmp/test.sh install_rpm"
        docker exec dockerInstance bash -c "/tmp/test.sh create_route"
        docker exec dockerInstance bash -c "/tmp/test.sh test_route"
        docker rm -f dockerInstance

    - name: run ubuntu docker containers for test
      run: |
        docker run -itd --rm \
            -v ${PWD}/output:/tmp/output \
            -v ${PWD}/test.sh:/tmp/test.sh \
            --name dockerInstance \
            --net="host" \
            docker.io/ubuntu:18.04 /bin/bash

    - name: run ubuntu test
      run: |
        docker exec dockerInstance bash -c "/tmp/test.sh install_deb"
        docker exec dockerInstance bash -c "/tmp/test.sh create_route"
        docker exec dockerInstance bash -c "/tmp/test.sh test_route"
        docker rm -f dockerInstance
