name: package apisix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          sudo apt-get install -y rpm

      - name: run apisix packaging test
        run: |
          make package type=rpm app=apisix version=2.3 checkout=2.3
          make package type=rpm app=apisix version=2.2 checkout=v2.2
          make package type=rpm app=apisix version=master checkout=master
