name: package apisix-runtime deb for ubuntu 20.04 with openresty 1.21

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      BUILD_APISIX_RUNTIME_VERSION: 1.1.2
      ARCH : amd64
    strategy:
      matrix:
        platform:
           - linux/amd64
           - linux/arm64
    steps:
      - uses: actions/checkout@v2
        with:
          ref: openresty/1.21.4
      - name: set env.ARCH if platform.arch is aarch64
        run: |
          if [ "${{ matrix.platform }}" == "linux/arm64" ]; then
            echo "ARCH=arm64" >> $GITHUB_ENV
          fi
      - name: check arch
        run: |
          echo "ARCH: ${{ env.ARCH }}"
      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential

      - name: build apisix-runtime deb
        run: |
          if [ "${{ matrix.platform }}" == "linux/arm64" ]; then
            make package type=deb app=apisix-runtime runtime_version=${BUILD_APISIX_RUNTIME_VERSION} image_base=debian image_tag=bullseye-slim arch=${{ matrix.platform }}
          else
            make package type=deb app=apisix-runtime runtime_version=${BUILD_APISIX_RUNTIME_VERSION} image_base=debian image_tag=bullseye-slim arch=${{ matrix.platform }}
          fi

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: apisix-runtime_${{ env.BUILD_APISIX_RUNTIME_VERSION }}-0~ubuntu20.04_${{ env.ARCH }}.deb
          path: output/apisix-runtime_${{ env.BUILD_APISIX_RUNTIME_VERSION }}-0~ubuntu20.04_${{ env.ARCH }}.deb
          retention-days: 5
          if-no-files-found: error